### ISSUE TITLE
Support for the raw option in screens configuration

### ISSUE THREAD

**Issue by ElMassimo** [voorjaar/windicss#15]
### Description 📖 

When using the [`raw` option to define media queries](https://tailwindcss.com/docs/breakpoints#styling-for-print) in `screens`, the CSS generated by windicss for these rules is incorrect.

Any class that uses a modifier defined using `raw`, such as

```js
screens: {
  print: { raw: 'print' },
},
``` 

will render that object since the code is expecting a string:

```css
@media (min-width: [object Object]) {
  .print\:hidden {
    display: none;
  }
}
``` 

Would you accept a PR implementing this behavior?

### Notes 📝 

I'm using it from [vite](https://github.com/antfu/vite-plugin-windicss), which uses the __`interpret` mode__.
